# Generated by Django 5.1.3 on 2025-05-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField()),
                ('reminder_method', models.CharField(choices=[('SMS', 'Text Message'), ('EMAIL', 'Email Message')], max_length=10)),
            ],
        ),
    ]
